export const CRYPTO_TICKERS = [
  {
    ticker: 'BTC/EUR',
    krakenPair: 'BTCEUR',
    name: 'Bitcoin',
    sector: 'Criptovalute',
    description: 'Asset digitale decentralizzato con maggiore capitalizzazione e liquidità.',
  },
  {
    ticker: 'ETH/EUR',
    krakenPair: 'ETHEUR',
    name: 'Ethereum',
    sector: 'Smart contract',
    description: 'Rete blockchain programmabile usata per applicazioni decentralizzate.',
  },
  {
    ticker: 'SOL/EUR',
    krakenPair: 'SOLEUR',
    name: 'Solana',
    sector: 'Smart contract',
    description: 'Blockchain ad alta velocità orientata ad applicazioni e finanza decentralizzata.',
  },
  {
    ticker: 'ADA/EUR',
    krakenPair: 'ADAEUR',
    name: 'Cardano',
    sector: 'Smart contract',
    description: 'Protocollo blockchain proof-of-stake con sviluppo accademico e modulare.',
  },
  {
    ticker: 'XRP/EUR',
    krakenPair: 'XRPEUR',
    name: 'XRP',
    sector: 'Pagamenti',
    description: 'Asset digitale orientato a trasferimenti rapidi e infrastrutture di pagamento.',
  },
  {
    ticker: 'DOT/EUR',
    krakenPair: 'DOTEUR',
    name: 'Polkadot',
    sector: 'Interoperabilità',
    description: 'Rete progettata per connettere blockchain diverse tramite parachain.',
  },
  {
    ticker: 'LINK/EUR',
    krakenPair: 'LINKEUR',
    name: 'Chainlink',
    sector: 'Oracoli',
    description: 'Rete di oracoli che collega dati esterni e smart contract.',
  },
  {
    ticker: 'LTC/EUR',
    krakenPair: 'LTCEUR',
    name: 'Litecoin',
    sector: 'Pagamenti',
    description: 'Criptovaluta storica focalizzata su pagamenti rapidi e costi contenuti.',
  },
  {
    ticker: 'BCH/EUR',
    krakenPair: 'BCHEUR',
    name: 'Bitcoin Cash',
    sector: 'Pagamenti',
    description: 'Fork di Bitcoin orientato a transazioni on-chain a basso costo.',
  },
  {
    ticker: 'ATOM/EUR',
    krakenPair: 'ATOMEUR',
    name: 'Cosmos',
    sector: 'Interoperabilità',
    description: 'Ecosistema blockchain modulare basato su comunicazione tra chain.',
  },
  {
    ticker: 'AVAX/EUR',
    krakenPair: 'AVAXEUR',
    name: 'Avalanche',
    sector: 'Smart contract',
    description: 'Piattaforma per applicazioni decentralizzate e subnet blockchain.',
  },
  {
    ticker: 'ETC/EUR',
    krakenPair: 'ETCEUR',
    name: 'Ethereum Classic',
    sector: 'Smart contract',
    description: 'Blockchain proof-of-work nata dalla rete storica Ethereum.',
  },
  {
    ticker: 'TRX/EUR',
    krakenPair: 'TRXEUR',
    name: 'TRON',
    sector: 'Smart contract',
    description: 'Rete blockchain focalizzata su trasferimenti digitali e stablecoin.',
  },
  {
    ticker: 'XLM/EUR',
    krakenPair: 'XLMEUR',
    name: 'Stellar',
    sector: 'Pagamenti',
    description: 'Rete per pagamenti e trasferimenti cross-border a basso costo.',
  },
  {
    ticker: 'DOGE/EUR',
    krakenPair: 'DOGEEUR',
    name: 'Dogecoin',
    sector: 'Pagamenti',
    description: 'Asset digitale ad alta notorietà e volatilità, nato come meme coin.',
  },
  {
    ticker: 'UNI/EUR',
    krakenPair: 'UNIEUR',
    name: 'Uniswap',
    sector: 'DeFi',
    description: 'Token di governance collegato a uno dei principali exchange decentralizzati.',
  },
  {
    ticker: 'AAVE/EUR',
    krakenPair: 'AAVEEUR',
    name: 'Aave',
    sector: 'DeFi',
    description: 'Protocollo decentralizzato per prestiti e liquidità crypto.',
  },
  {
    ticker: 'ALGO/EUR',
    krakenPair: 'ALGOEUR',
    name: 'Algorand',
    sector: 'Smart contract',
    description: 'Blockchain proof-of-stake orientata a scalabilità e finalità rapida.',
  },
]
