export const EUROPEAN_TICKERS = [
  'ENEL.MI',
  'ISP.MI',
  'RACE.MI',
  'STLAM.MI',
  'UCG.MI',
  'ENI.MI',
  'TIT.MI',
  'G.MI',
  'PRY.MI',
  'MONC.MI',
  'LDO.MI',
  'BAMI.MI',
  'BPE.MI',
  'SRG.MI',
  'TRN.MI',
  'AIR.PA',
  'OR.PA',
  'MC.PA',
  'TTE.PA',
  'SAN.PA',
  'BNP.PA',
  'AI.PA',
  'RMS.PA',
  'CS.PA',
  'DG.PA',
  'RI.PA',
  'SU.PA',
  'CAP.PA',
  'EN.PA',
  'ACA.PA',
  'SAP.DE',
  'SIE.DE',
  'ALV.DE',
  'DTE.DE',
  'MBG.DE',
  'BMW.DE',
  'VOW3.DE',
  'BAS.DE',
  'BAYN.DE',
  'MUV2.DE',
  'ADS.DE',
  'DHL.DE',
  'DBK.DE',
  'IFX.DE',
  'RWE.DE',
  'ASML.AS',
  'ADYEN.AS',
  'INGA.AS',
  'PHIA.AS',
  'HEIA.AS',
  'AKZA.AS',
  'WKL.AS',
  'NN.AS',
  'SAN.MC',
  'BBVA.MC',
  'IBE.MC',
  'ITX.MC',
  'REP.MC',
  'TEF.MC',
  'FER.MC',
  'CABK.MC',
  'NESN.SW',
  'NOVN.SW',
  'ROG.SW',
  'UBSG.SW',
  'ZURN.SW',
  'SIKA.SW',
  'ABBN.SW',
  'GIVN.SW',
  'VOLV-B.ST',
  'ERIC-B.ST',
  'HM-B.ST',
  'INVE-B.ST',
  'ATCO-A.ST',
  'NOVO-B.CO',
  'MAERSK-B.CO',
  'DSV.CO',
  'NDA-FI.HE',
  'KNEBV.HE',
  'EQNR.OL',
]

export const US_TICKERS = [
  'AAPL.US',
  'MSFT.US',
  'NVDA.US',
  'AMZN.US',
  'META.US',
  'GOOGL.US',
  'TSLA.US',
  'AVGO.US',
  'JPM.US',
  'V.US',
  'MA.US',
  'UNH.US',
  'LLY.US',
  'XOM.US',
  'COST.US',
  'HD.US',
  'PG.US',
  'NFLX.US',
  'AMD.US',
  'CRM.US',
  'ORCL.US',
  'ADBE.US',
  'BAC.US',
  'KO.US',
  'PEP.US',
  'MRK.US',
  'WMT.US',
  'MCD.US',
  'CSCO.US',
  'INTC.US',
]

export const ASIA_TICKERS = [
  '7203.TSE',
  '6758.TSE',
  '9984.TSE',
  '8306.TSE',
  '6861.TSE',
  '8035.TSE',
  '9432.TSE',
  '6098.TSE',
  '6501.TSE',
  '4063.TSE',
  '0700.HK',
  '9988.HK',
  '3690.HK',
  '1299.HK',
  '0939.HK',
  '1398.HK',
  '2318.HK',
  '0388.HK',
  '0005.HK',
  '0941.HK',
]

const TICKER_CURRENCY_SUFFIXES = [
  { suffix: '.US', currency: 'USD' },
  { suffix: '.TSE', currency: 'JPY' },
  { suffix: '.HK', currency: 'HKD' },
  { suffix: '.SW', currency: 'CHF' },
  { suffix: '.ST', currency: 'SEK' },
  { suffix: '.CO', currency: 'DKK' },
  { suffix: '.OL', currency: 'NOK' },
]

export function getTickerCurrency(ticker) {
  const value = String(ticker || '').toUpperCase()
  const match = TICKER_CURRENCY_SUFFIXES.find(({ suffix }) =>
    value.endsWith(suffix),
  )

  return match?.currency || 'EUR'
}

export const MARKET_UNIVERSES = {
  europe: EUROPEAN_TICKERS,
  equities: EUROPEAN_TICKERS,
  usa: US_TICKERS,
  asia: ASIA_TICKERS,
}
