create table if not exists public.spapple_state_events (
  id bigint generated by default as identity primary key,
  state_id text not null default 'default',
  revision bigint not null,
  source text not null default 'server',
  summary text not null default 'Stato Spapple aggiornato',
  created_at timestamptz not null default now()
);

alter table public.spapple_state_events enable row level security;

grant select on public.spapple_state_events to anon;
grant select on public.spapple_state_events to authenticated;
grant insert on public.spapple_state_events to service_role;
grant usage, select on sequence public.spapple_state_events_id_seq to service_role;

drop policy if exists "spapple_state_events_read" on public.spapple_state_events;

create policy "spapple_state_events_read"
on public.spapple_state_events
for select
to anon, authenticated
using (state_id = 'default');

do $$
begin
  alter publication supabase_realtime add table public.spapple_state_events;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
