-- Schema PostgreSQL per Spapple su Neon
-- Eseguire questo script nel SQL Editor di Neon

CREATE TABLE IF NOT EXISTS public.spapple_state (
  id TEXT PRIMARY KEY DEFAULT 'default',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.spapple_state_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_id TEXT NOT NULL DEFAULT 'default',
  revision BIGINT NOT NULL,
  source TEXT NOT NULL DEFAULT 'server',
  summary TEXT NOT NULL DEFAULT 'Stato Spapple aggiornato',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spapple_state_events_state_id_created 
ON public.spapple_state_events (state_id, created_at);
